version: '3'

services:
  redis:
    image: redis:latest
    container_name: test_redis
    restart: always
  db:
    image:  "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
    command:
      --lower_case_table_names=1
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ./sqldata:/var/lib/mysql
  api:
    image: testapi:0.01
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
      args:
        JAR_RELEASE_PATH: document-system-0.0.1-SNAPSHOT.jar
    ports:
      - 8098:8080
    depends_on:
      - db
      - redis
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      #spring.profiles.active: prod
      global.remark: 服务端变量
      file.encoding: utf-8
      server.port: 8080
      spring.datasource.password: test
      spring.redis.host: redis
      spring.datasource.url: jdbc:mysql://db:3306/test?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      CONTAINER_TIMEZONE: Asia/Shanghai


