spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MyUploader?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

global:
  remark: 本地变量

logging:
  file:
    name: log/dev.log

